# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='init_avg_daily_tips',
            field=models.IntegerField(default=0),
        ),
    ]
