# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_auto_20170413_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoutuser',
            name='city',
            field=models.CharField(default='none', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoutuser',
            name='state',
            field=models.CharField(default='none', max_length=40),
            preserve_default=False,
        ),
    ]
