# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_auto_20170417_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoutuser',
            name='stripe_coupon',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
