# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_tipoutuser_stripe_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoutuser',
            old_name='stripe_coupon',
            new_name='coupon',
        ),
    ]
