# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_auto_20170522_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoutuser',
            name='coupon',
            field=models.CharField(default='', max_length=16),
        ),
    ]
