# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-28 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_auto_20170528_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoutuser',
            name='coupon',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
