# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_auto_20170528_1451'),
        ('custom_auth', '0006_auto_20170605_0814'),
    ]

    operations = [
    ]
