# Generated by Django 3.1.3 on 2020-11-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0008_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoutuser',
            name='coupon',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
