# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='init_avg_daily_tips',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='employee',
            name='new_user',
            field=models.BooleanField(default=True),
        ),
    ]
