# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-06 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date_added',
        ),
    ]
