# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='name',
            new_name='expense_name',
        ),
    ]
