# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-06 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0002_remove_expense_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 5, 6, 11, 27, 35, 662029)),
            preserve_default=False,
        ),
    ]
