# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 21:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0002_auto_20170413_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='signup_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 20, 21, 11, 7, 761019, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 20, 21, 11, 7, 779513, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='date_earned',
            field=models.DateField(default=datetime.datetime(2017, 4, 20, 21, 11, 7, 776529, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tip',
            name='date_earned',
            field=models.DateField(default=datetime.datetime(2017, 4, 20, 21, 11, 7, 775766, tzinfo=utc)),
        ),
    ]
