# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0003_auto_20170420_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='signup_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='date_earned',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tip',
            name='date_earned',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
