# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0004_auto_20170420_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('BI_WEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly'), ('ANNUALLY', 'Annually')], default='MONTHLY', max_length=9),
        ),
    ]
