# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0004_auto_20170509_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='savings_each_day',
        ),
        migrations.AddField(
            model_name='employee',
            name='savings_percent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
