# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 05:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0005_auto_20160222_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='signup_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
