# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0005_auto_20170513_1333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavingsTransactions',
            new_name='SavingsTransaction',
        ),
    ]
