# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-28 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0005_auto_20170422_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='daily_budget',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='budget',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='budget',
            name='over_under',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly'), ('ANNUALLY', 'Annually')], default='MONTHLY', max_length=9),
        ),
    ]
