# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0006_auto_20160222_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='init_avg_daily_tips',
            field=models.IntegerField(),
        ),
    ]
