# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-20 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0006_auto_20170513_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='tipout.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='OtherFunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date_earned', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otherincome', to='tipout.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='last_paid_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
