# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 13:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0006_auto_20170428_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='dated_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 5, 4, 13, 49, 13, 816799)),
            preserve_default=False,
        ),
    ]
