# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-20 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0007_auto_20170520_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='last_paid_on',
            new_name='paid_on',
        ),
    ]
