# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0007_expense_dated_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='dated_added',
            new_name='date_added',
        ),
    ]
