# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0008_expense_date_added'),
        ('tipout', '0008_auto_20170504_1651'),
    ]

    operations = [
    ]
