# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0009_auto_20170520_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
