# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0009_auto_20160227_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='note',
            field=models.CharField(default='expenditure', max_length=100),
        ),
    ]
