# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0011_auto_20160317_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='earns_tips',
        ),
    ]
