# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-09 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0012_remove_employee_earns_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='init_avg_daily_tips',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tip',
            name='amount',
            field=models.FloatField(),
        ),
    ]
