# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 01:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('tipout', '0013_auto_20170409_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('id', models.CharField(max_length=50)),
                ('plan', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='signup_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
