# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0013_auto_20170408_1805'),
        ('tipout', '0014_auto_20170410_0159'),
    ]

    operations = [
    ]
