# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0018_auto_20170410_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_subscribed',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
