# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0019_auto_20170410_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='daily_budget',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='employee',
            name='init_avg_daily_tips',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='expense',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='tip',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='tip',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=9),
        ),
    ]
