# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipout', '0020_auto_20170412_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AlterField(
            model_name='budget',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='tipout.Employee'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='tipout.Employee'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tipout.Employee'),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paychecks', to='tipout.Employee'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='tipout.Employee'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
